backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow
local_backend: false

# оставьте ваши коллекции как были; ниже пример
collections:
  - name: "posts"
    label: "Статьи"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Обложка", name: "cover", widget: "image", required: false }
      - { label: "Текст", name: "body", widget: "markdown" }
