backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", default: "{{now}}"}
      - {label: "Author", name: "author", widget: "string", default: "Flamingo Auto"}
      - {label: "Language", name: "lang", widget: "select", options: ["ru", "et", "en"], default: "ru"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "text", required: true}