backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

publish_mode: simple
locale: "ru"

collections:
  - name: "blog"
    label: "📝 Статьи блога"
    label_singular: "Статья"
    description: "Создание и управление статьями блога"
    folder: "content/blog"
    extension: "md"
    format: "yaml-frontmatter"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    
    fields:
      - label: "Заголовок"
        name: "title"
        widget: "string"
        hint: "Заголовок статьи"

      - label: "Дата"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        hint: "Дата публикации"

      - label: "Автор"
        name: "author"
        widget: "string"
        default: "Flamingo Auto"
        hint: "Автор статьи"

      - label: "Язык"
        name: "lang"
        widget: "select"
        options: 
          - { label: "Русский", value: "ru" }
          - { label: "Эстонский", value: "et" }
          - { label: "Английский", value: "en" }
        default: "ru"

      - label: "Опубликовано"
        name: "published"
        widget: "boolean"
        default: true

      - label: "Содержание"
        name: "body"
        widget: "markdown"
        hint: "Основной текст статьи"